### ISSUE TITLE
React helmet

### ISSUE THREAD

**Issue by mistakenelf** [alexknipfer/DiscShareClient#7]
Use react helmet for page titles and SEO value.

**Comment by M-ZubairAhmed** [comment]
hi,
do you want help with this issue and can you provide more information regarding this issue

**Comment by mistakenelf** [comment]
@M-ZubairAhmed  Sure, would love help. Would like to get react-helmet added and then inside of each route on the main view for that route, would like to have the page title, description etc added. 

CC: @alexknipfer
